/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: spider-zip3 (https://sketchfab.com/spider-zip3)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/ironman-mark-85-custom-painted-afa7b04bdc4e479c8c7d420aae734405
title: Ironman Mark 85 Custom Painted
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ironman2.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group scale={83.37}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
              <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                <group position={[148.26, 229.64, 2.62]}>
                  <mesh geometry={nodes.Subdivision_Surface_893_Mat_2_0_2.geometry} material={materials.Mat_2} />
                  <mesh geometry={nodes.Subdivision_Surface_893_Mat_2_0_3.geometry} material={materials.Mat_2} />
                </group>
                <group position={[101.04, 211.94, 16.96]}>
                  <mesh geometry={nodes.Subdivision_Surface_894_Mat_0_11.geometry} material={materials.material} />
                  <mesh geometry={nodes.Subdivision_Surface_894_Mat_0_12.geometry} material={materials.material} />
                  <mesh geometry={nodes.Subdivision_Surface_894_Mat_0_13.geometry} material={materials.material} />
                  <mesh geometry={nodes.Subdivision_Surface_894_Mat_0_14.geometry} material={materials.material} />
                  <mesh geometry={nodes.Subdivision_Surface_894_Mat_0_15.geometry} material={materials.material} />
                  <mesh geometry={nodes.Subdivision_Surface_894_Mat_0_16.geometry} material={materials.material} />
                  <mesh geometry={nodes.Subdivision_Surface_894_Mat_0_17.geometry} material={materials.material} />
                  <mesh geometry={nodes.Subdivision_Surface_894_Mat_0_18.geometry} material={materials.material} />
                  <mesh geometry={nodes.Subdivision_Surface_894_Mat_0_19.geometry} material={materials.material} />
                  <mesh geometry={nodes.Subdivision_Surface_894_Mat_0_20.geometry} material={materials.material} />
                  <mesh geometry={nodes.Subdivision_Surface_894_Mat_0_21.geometry} material={materials.material} />
                </group>
                <group position={[57.74, 225.55, -10.71]}>
                  <mesh geometry={nodes.Subdivision_Surface_379_Mat_1_0_7.geometry} material={materials.Mat_1} />
                  <mesh geometry={nodes.Subdivision_Surface_379_Mat_1_0_8.geometry} material={materials.Mat_1} />
                  <mesh geometry={nodes.Subdivision_Surface_379_Mat_1_0_9.geometry} material={materials.Mat_1} />
                  <mesh geometry={nodes.Subdivision_Surface_379_Mat_1_0_10.geometry} material={materials.Mat_1} />
                  <mesh geometry={nodes.Subdivision_Surface_379_Mat_1_0_11.geometry} material={materials.Mat_1} />
                  <mesh geometry={nodes.Subdivision_Surface_379_Mat_1_0_12.geometry} material={materials.Mat_1} />
                  <mesh geometry={nodes.Subdivision_Surface_379_Mat_1_0_13.geometry} material={materials.Mat_1} />
                </group>
                <group position={[143.3, 245.67, 7.44]}>
                  <mesh geometry={nodes.________________________________________________________________________________3__________________________________________________6_0_1.geometry} material={materials.material_3} />
                </group>
                <group position={[0, 268.18, 43.95]} rotation={[1.29, 0, 0]}>
                  <mesh geometry={nodes.___________________________________________5__________________________________________________7_0_1.geometry} material={materials.material_4} />
                </group>
                <group position={[-62.73, 188.62, 23.53]} rotation={[0.82, 0.34, -0.58]}>
                  <mesh geometry={nodes.Retopo_Subdivision_Surface_831__________________________________________________5_0_1.geometry} material={materials.material_5} />
                </group>
                <group position={[-81.24, 168.2, 11.13]} rotation={[1.79, 0.27, 1.69]}>
                  <mesh geometry={nodes.Retopo_Subdivision_Surface_830__________________________________________________4_0_1.geometry} material={materials.material_6} />
                </group>
                <group position={[-81.98, 168.29, 16.47]} rotation={[1.54, 0.3, 1.54]}>
                  <mesh geometry={nodes.Retopo_Subdivision_Surface_829__________________________________________________1_0_1.geometry} material={materials.material_7} />
                </group>
                <group position={[-80.02, 171.82, 26.56]} rotation={[1.46, 0.08, 1.16]}>
                  <mesh geometry={nodes.Retopo_Subdivision_Surface_828__________________________________________________2_0_1.geometry} material={materials.material_8} />
                </group>
                <group position={[-81.51, 169.52, 21.85]} rotation={[1.48, 0.22, 1.39]}>
                  <mesh geometry={nodes.Retopo_Subdivision_Surface_827__________________________________________________3_0_1.geometry} material={materials.material_9} />
                </group>
                <group position={[-82.35, 180.47, 16.03]} rotation={[1.31, 0.02, 1.44]}>
                  <mesh geometry={nodes.Retopo_Subdivision_Surface_826__________________________________________________0_1.geometry} material={materials.material_10} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/ironman2.gltf')
