/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: benjamin.borromeo (https://sketchfab.com/benjamin.borromeo)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/iron-man-mark-7subsurf-a13c067e70814dc7b2ebc3f0ace10961
title: Iron Man Mark-7(Subsurf)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/ironman.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI/2, 0, 0]} >
        <group position={[0,0,-3]} scale={3}>
          <lineSegments geometry={nodes.Object_2.geometry} material={materials.ArcReactor} />
          <mesh geometry={nodes.Object_3.geometry} material={materials.ArcReactor} />
          <mesh geometry={nodes.Object_4.geometry} material={materials.Eyes} />
          <mesh geometry={nodes.Object_5.geometry} material={materials.Glass} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.Blue} />
          <mesh geometry={nodes.Object_7.geometry} material={materials.Gold} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.Repulsor} />
          <mesh geometry={nodes.Object_9.geometry} material={materials.material} />
          <mesh geometry={nodes.Object_10.geometry} material={materials.material} />
          <mesh geometry={nodes.Object_11.geometry} material={materials.Black} />
          <mesh geometry={nodes.Object_12.geometry} material={materials.Silver} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/ironman.gltf')
